### ISSUE TITLE
filebeat modules

### ISSUE THREAD

**Issue by Jennnifers** [josh-thurston/easyBEATS#3]
Thanks for your script for making it easy to install beats on a Raspberry Pi!  This saved me a ton of time!

I just wanted to post a suggested workaround to your issue - specifically for filebeat:

> Some of the beats products use 'modules' to extend functionality. Typically you can type something similar to "filebeat modules enable osquery" to enable and use the module. I have not been able to get that command to work. To use the modules, you will need to configure the module inside the configuration file. 

I got the filebeat modules working by changing the filebeat.yml to point to the absolute path to the modules.d directory:

```
#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  #path: ${path.config}/modules.d/*.yml
  path: /etc/filebeat/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s
```
